PREFIX : <http://purl.org/net/rr/RelativeRelationshipPattern#>
PREFIX d: <http://rr-pattern.example/data#>
PREFIX v: <http://rr-pattern.example/extvocab#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX u:   <http://learningsparql.com/ns/units#>

SELECT DISTINCT ?building_name ?factor_number ?ref #?x ?prop_type
WHERE { ?building_name rdf:type :RelativeExistence .
	d:PhysicalScaleDescription a :RelationshipDescription .
	d:PhysicalScaleDescription :hasOrigin d:Building_1_Instance; :hasTarget d:Building_2_Instance .
        d:PhysicalScaleDescription ?ref ?building_name .
	?x rdf:type :Property .
	?building_name :determinedBy ?x .
	?prop_type rdf:type ?x; d:hasType d:Factor; d:hasValue ?factor_number }


# Expected:
# ?building_name      ?factor_number    ?ref
# "Building2Model"    "0.5"             :hasTarget
# "Building1Model"    “2.0”             :hasOrigin



