PREFIX : <http://purl.org/net/rr/RelativeRelationshipPattern#>
PREFIX d: <http://rr-pattern.example/data#>
PREFIX v: <http://rr-pattern.example/extvocab#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX u:   <http://learningsparql.com/ns/units#>

SELECT ?building_name ?coordinate_set
WHERE { ?building_name rdf:type :Entity .
	d:CoordinateSet rdf:type ?x; d:hasValue ?coordinate_set }

# Expected:
# ?building_name      ?coordinate_set
# "Building2Model"    "IFC_File"
# "Building1Model"    "CAD_File"


